# Generated by Django 2.2.5 on 2019-09-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
