# Generated by Django 2.2.5 on 2019-09-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0002_remove_message_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
